#!/usr/bin/env python

import mapclassify as mc
import matplotlib.pyplot as plt
import pandas as pd
import geopandas as gpd
import geoplot as gplt
import geoplot.crs as gcrs

# 1) Load datacenter data.
datacenters_json = pd.read_json("data/datacenters.json")
# Turn dataframe into a geo-capable dataframe, with lon/lat geometry.
# See: https://geopandas.org/gallery/create_geopandas_from_pandas.html
datacenters = gpd.GeoDataFrame(
    datacenters_json,
    geometry=gpd.points_from_xy(datacenters_json.longitude, datacenters_json.latitude),
    crs="EPSG:4326",  # Standard lon/lat coordinate reference system (CRS)
)

# 2) Draw USA West basemap.
# Only keep states from the US "West" states as defined here (states of interest):
# https://droughtmonitor.unl.edu/CurrentMap/StateDroughtMonitor.aspx?West
contiguous_usa = gpd.read_file(gplt.datasets.get_path("contiguous_usa"))
west_states = [
    "California",
    "Nevada",
    "Oregon",
    "Washington",
    "Idaho",
    "Montana",
    "Utah",
    "Arizona",
    "New Mexico",
]
us_west = contiguous_usa[contiguous_usa.state.isin(west_states)]
ax = gplt.polyplot(
    us_west,
    projection=gcrs.AlbersEqualArea(),
    linewidth=0.5,
    zorder=1,
)

# 3) Overlay drought data.
# Source data URL found here: https://droughtmonitor.unl.edu/DmData/GISData.aspx
# `drought` contains 5 rows, one per drought intensity, each associated
# with a multi-polygon that contains the set of areas at that drought level.
drought_url = "https://droughtmonitor.unl.edu/data/shapefiles_m/USDM_20210622_M.zip"
drought = gpd.read_file(drought_url)
drought["intensity"] = drought["DM"]  # Rename ambiguous column.
# TODO: select drought data within `us_west` only.

# Draw drought areas colored by drought intensity.
# See: https://residentmario.github.io/geoplot/plot_references/plot_reference.html#choropleth
gplt.choropleth(
    drought,
    hue="intensity",
    cmap="YlOrRd",  # Light yellow to dark red
    legend=True,
    scheme=mc.FisherJenks(drought["intensity"], k=5),  # 5-category legend
    legend_kwargs={"bbox_to_anchor": (1, 0.35)},
    legend_labels=[
        "D0 (Abnormally Dry)",
        "D1 (Moderate Drought)",
        "D2 (Severe Drought)",
        "D3 (Extreme Drought)",
        "D4 (Exceptional Drought)",
    ],
    ax=ax,
    zorder=0,
)

# 4) Overlay datacenters in US West on map.
datacenters_west = gpd.sjoin(datacenters, us_west, how="inner")
gplt.pointplot(
    datacenters_west,
    ax=ax,
    zorder=2,
)

plt.savefig("out/result.svg")
